import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProviderWrapper from "./ProviderWrapper";

export const metadata: Metadata = {
  title: "Rn-Eats",
  description: "Generated by rn-Eats",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="light"
      style={{ colorScheme: "light" }}
    >
      <body className={`relative antialiased`}>
        <ProviderWrapper>{children}</ProviderWrapper>
      </body>
    </html>
  );
}
